### ISSUE TITLE
transId keeping unique ids issue 

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#20]
Hello, 

some genes are not changed to the new symbols (the new symbol is BABAM2):
<img width="160" alt="image" src="https://github.com/GangLiLab/genekitr/assets/16545437/0db7de9a-5c7d-400d-85d2-af01be7e0502">

Also, the information of the genee is not complete:
<img width="825" alt="image" src="https://github.com/GangLiLab/genekitr/assets/16545437/d94bac1d-b62a-4c1f-8728-9543f05c9db8">

**Comment by reedliu** [comment]
Hi, thanks for your feedback. 
This issue is because we imported protein ID data from Uniprot, but the gene symbols in Uniprot are mixed. For example, the name BRE alone contains two Uniprot IDs: [L8E9D4](https://www.uniprot.org/uniprotkb/L8E9D4/entry) and [Q96P08](https://www.uniprot.org/uniprotkb/Q96P08/entry). However, there is indeed a bug when dealing with one-to-many mapping. The previous logic for determining this was: if the same symbol appears, then keep the record with the same symbol.

The bug is fixed in version 1.2.4, please try again.

```
transId(c('BEX1','BRE','BTG2','C14orf169'),'sym',unique = T,keepNA = T)
```
<img width="711" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/81582aea-7062-4da1-aa89-343a910f2f60">


For your second question, could you please provide example data (7666 genes you mentioned) for testing? Because if we use all human symbols in HGNC website, the results are same:
```
all = vroom::vroom('https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt')
all_sym = unique(all$symbol)
length(all_sym)

x = genInfo(all_sym,unique = T,keepNA = T)
table(x$input_id %in% all_sym)
table(all_sym %in% x$input_id)
```

<img width="680" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/22f5aac1-c2f0-4748-bb5d-bfd3a28914dd">
