### ISSUE TITLE
new version is memory hungry

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#7]
Hello--

In the previous version, I used to convert 30k gene symbols in one command on my machine with 32GB and never had a problem. Now, when I try to run the same command (transId) on the same symbols, even a machine with 128GN will kill the process as the memory is not enough.

**Comment by reedliu** [comment]
Hi,
The new version didn't change main functions. It just utilized new backend data. So i think it may not be the real problem since you tested on last machine successfully.
For your new machine, please check R memory limit setting following the link, https://stackoverflow.com/questions/1395229/increasing-or-decreasing-the-memory-available-to-r-processes. If things happens, please try to use small sets to run transId on the new machine and see if it works.

**Comment by reedliu** [comment]
I have tested ~56k mouse ensembl IDs (from gencode.vM32.annotation.gtf) and used transId to convert to symbols.
Seems that it did not consume much memory.
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/34302878/226217150-0b71fd71-505c-48d5-8372-b431feae2003.png">

**Comment by reedliu** [comment]
I have tested your sample file and no memory problem.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/34302878/226217731-6fca55cc-79af-4609-9cc4-c2ccbac3b393.png">

**Comment by reedliu** [comment]
Ah, I was running on another R 4.0 machine (genekitr v1.1.0). 
After changing to v1.1.3, I found this problem because of a typo in symbol IDs converting function(merge() => imerge() 😖).
Anyway, it is fixed now and you could try to install the v1.1.4 developmental version `remotes::install_github("GangLiLab/genekitr")`. The new version will be available soon on CRAN.
Thanks for your feedback and sorry for any inconvenience.
